#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "mpcs52015.cs.uchicago.edu";
$SERVER_PORT = 8181;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
